### ISSUE TITLE
Connect to a room?

### ISSUE THREAD

**Issue by oncletom** [charltoons/hipchatter#18]
Hello,

thanks for this library :-)
Through the doc (and HipChat API doc), I cannot find a way to understand how to join a room/send a message.

I'd like to have a bot which joins a room and can respond to user public messages.

Even through the webhook mechanism I don't see how my user/bot would be part of the list of the room members.

Thanks!

**Comment by csanner** [comment]
This library is for using the hipchat API  - for joining rooms and replying to general messages in the chat you want to use the hipchat connector located at https://github.com/hipchat/hubot-hipchat
there are some bugs but mostly it's functional and works fine for me

**Comment by oncletom** [comment]
@csanner ok thanks! I had a look at it but as it uses the xmpp channel, I was not sure if I understood all the things.
