### ISSUE TITLE
Invalid OAuth session

### ISSUE THREAD

**Issue by khanshakeeb** [charltoons/hipchatter#19]
Hi,

I am using hipchatter api and trying to hit room list but getting this error

Invalid OAuth session

Please guide me what is wrong with my implementation.

                               var authKey = "5127be0d2b4e119058ade9251ada5b";
				var notifyKey = "83iYDzb1I8U4CZfTtDO058hH08w9zHq8ZRC6wsmh";
				var hipchatter = new Hipchatter(authKey);
				// this will list all of your rooms
				hipchatter.rooms(function(err, rooms) {
					if (!err) {
						console.log(rooms)
					}else{
						console.log(err);
					}
				});

**Comment by maikdiepenbroek** [comment]
Hi @khanshakeeb, too bad it isn't working for you. 

Have you read this page: https://www.hipchat.com/docs/apiv2/auth

Could you please provide more info on the use case ?

**Comment by joshuaconner** [comment]
I had this exact issue and told HipChat to regenerate my personal access token, which fixed it.

**Comment by maikdiepenbroek** [comment]
@joshuaconner That's what i expected, be sure to try this @khanshakeeb.

**Comment by charltoons** [comment]
Closing from inactivity, please reopen if you still need help.
